name: Fabrica de IPA RBA 
on: 
  workflow_dispatch: # Isso permite que você aperte um botão para gerar quando quiser

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalando Ferramentas de Construção
        run: |
          npm install -g @ionic/cli @capacitor/cli
          npm install

      - name: Criando o Casulo iOS
        run: |
          npx cap init "RBA" com.iartium.rba --web-dir .
          npx cap add ios
          npx cap sync ios

      - name: Compilando o IPA (Sem Assinatura)
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO \
                     archive -archivePath ./build/App.xcarchive
